import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { StudentsList } from "../src/components";
import { Box, Button, Grid, Stack, Typography } from '@mui/material';

const Home: NextPage = () => {
  return (
    <Grid
      minWidth={"100vh"}
      height={"100vh"}
    >
      {/* Header */}
      <Box
        width={"10%"}
        height={"100vh"}
        bgcolor="primary.main"
        position={"fixed"}
        right={0}
      >
        <Image src="/awana.jpeg" alt="Awana Logo" width={130} height={130} />
      </Box>
      <Head>
        <title>Awana Cohort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <Box
        width={"10%"}
        height={"100vh"}
        bgcolor="primary.main"
        position={"fixed"}
        left={0}
      >
        <Image src="/awana.jpeg" alt="Awana Logo" width={130} height={130} />
      </Box>

      {/* Render students */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          marginLeft: '2em'
        }}
      >
        <Typography
          variant='h4'
          sx={{ pr: 4 }}
        >
          Cohort Students
        </Typography>
        <div>
          <a href={"/student/new"} type={"button"}>
            <Button>
              ADD STUDENT INFO
            </Button>
          </a>
        </div>
      </div>
      <StudentsList />
    </Grid>
  )
}

export default Home
